
version: '3'
services:
  
  web:
    image: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/code
    working_dir: /code
    networks:
      - web_network
    command: bash -c "flask db upgrade && flask run --host=0.0.0.0"
  nginx:
    image: nginx:1.17
    ports:
      - "8000:80"
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - web_network
    restart: always
networks:
  web_network:
    driver: bridge
